### ISSUE TITLE
HUB: no device or entities

### ISSUE THREAD

**Issue by zolldi** [BenPru/luxtronik#246] opened 2024-04-03 17:41 UTC
added integration, 
restarted HA, 
seems to find my heatpump as "none LWC407"

at: 192.168.1.158
port: 8888

but: "no device or entities"

![image](https://github.com/BenPru/luxtronik/assets/18075338/5d3c5442-07c3-42b4-874b-6a989e79c361)

**Comment by BenPru** [comment] 2024-04-09 20:47
Which HA and which Integration Version do you use?
If you use HA>=2023.8 please use the beta version of the integration.

**Comment by pietklokke** [comment] 2024-04-16 14:23
I have the same issue. Read your beta suggestion installed newest beta today, but no effect - still no devices or entities.

**Comment by morpheus12** [comment] 2024-04-19 07:30
Same Problem here. I tried several times to use the newest Beta (Latest with HA 2024.3.1).
Auto Discovery is not working. Adding the Luxtronic manually by IP works to get the integration done but without device or entities (same as in the screenshot of @zolldi ).

Can i contribute with some infos?

**Comment by xfirestyle2k** [comment] 2024-04-21 13:31
Hey Folks, I do have the same issue.
I checked the logs, and I found some errors like below.

Logger: homeassistant.components.update
Source: helpers/entity_platform.py:755
integration: Update ([documentation](https://www.home-assistant.io/integrations/update), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+update%22))
First occurred: 15:24:27 (1 occurrences)
Last logged: 15:24:27

luxtronik2: Not adding entity with invalid device info: Invalid device info {'configuration_url': 'http://10.0.2.175/', 'default_manufacturer': 'Alpha Innotec', 'default_model': '', 'default_name': 'Heatpump', 'identifiers': {('luxtronik2', '330512_023_heatpump')}, 'manufacturer': 'Novelan', 'model': 'LD7', 'name': 'Heatpump 330512-023', 'suggested_area': 'Utility room', 'sw_version': 'V2.88.3'} for 'luxtronik2' config entry: device info needs to either describe a device, link to existing device or provide extra information.

System:
Core
2024.4.3
Supervisor
2024.04.0
Operating System
12.2
Frontend
20240404.2

**Comment by xfirestyle2k** [comment] 2024-04-21 14:29
Well... shame one me..
Looks like the order of the beta versions are a little bit off.. I installed a 2023 beta version... after upgrading to the lastest 2024 version it works perfectly fine :). 
@zolldi @morpheus12 please check HACS if you see an update, after updating to the latest version and restarting home assistant it just should work, even the auto discover worked.

**Comment by morpheus12** [comment] 2024-04-25 13:48
> Well... shame one me.. Looks like the order of the beta versions are a little bit off.. I installed a 2023 beta version... after upgrading to the lastest 2024 version it works perfectly fine :). @zolldi @morpheus12 please check HACS if you see an update, after updating to the latest version and restarting home assistant it just should work, even the auto discover worked.

@xfirestyle2k : YOU ARE GREAT! ! ! Now it works I'm so happy About!!!

Again thx to @BenPru for this great Plugin!

**Comment by PVAnfaenger** [comment] 2024-06-20 13:01
Hello, I am also in the process of integrating the project here. Since I had exactly the same problems as @zolldi, I noticed that the 2023 version is always downloaded. When updating to the 2024 version I get the following error message! Should I ignore it?

![Screenshot](https://github.com/BenPru/luxtronik/assets/147447750/8af3cf0e-9611-43a8-a29c-ed9b1d9f3764)

**Comment by PVAnfaenger** [comment] 2024-06-21 06:33
Hello,
there is another problem, doesn't really bother me, just wanted to let you know that the manufacturer Roth is not recognized. Or do you have to enter it yourself somewhere?

![ScreenshotHerstellerFehlt](https://github.com/BenPru/luxtronik/assets/147447750/95744ca0-7d1a-4b05-8232-ba17d08e691f)

**Comment by BenPru** [comment] 2024-06-30 13:07
@PVAnfaenger The manufacturer is requested from the underlying module https://github.com/Bouni/python-luxtronik.
As the problem is fixed I close this issue.

**Closed by BenPru** 2024-06-30 13:07 UTC
