### ISSUE TITLE
Sine Nov 29: Heatpump Status showing "Idle" --> State not detected correctly

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#44] opened 2022-12-01 07:17 UTC
Hi!

Something changed in implementation of LUX_Sensor_Status. Sensor is always showing idle for 2 days now.

**Comment by rhammen** [comment] 2022-12-01 07:37
Looks like a duplicate of #41

**Closed** 2022-12-01 08:00 UTC
